import { buildVerdict } from "./classify.ts";
import type { ApRadio, ClientEvent, ClientSession, ClientStats, DiagnoseResult } from "./types.ts";

const now = () => Math.floor(Date.now() / 1000);

export const DEMO_MAC = "a483e7129c4b";

export function buildDemoResult(opts?: { jitter?: boolean }): DiagnoseResult {
  const t = now();
  const jitter = opts?.jitter ? Math.round((Math.random() - 0.5) * 6) : 0;
  const stats: ClientStats = {
    mac: DEMO_MAC,
    hostname: "VALERIE-MBP",
    manufacture: "Apple",
    os: "macOS 15.5",
    model: "MacBookPro18,3",
    ssid: "CORP-WIFI",
    vlan: 40,
    ip: "10.40.12.88",
    ap: "5c5b350eb31b",
    band: "5",
    channel: 149,
    proto: "ax",
    rssi: -81 + jitter,
    snr: Math.max(6, 11 + Math.round(jitter / 2)),
    txRate: 58,
    rxRate: 48,
    uptime: 214,
    lastSeen: t - 12,
    txBytes: 1843200,
    rxBytes: 9216000,
    username: "vcowan",
    keyMgmt: "WPA2-PSK",
    txRetries: 214,
    rxRetries: 88,
    dualBand: true,
  };

  const events: ClientEvent[] = [
    {
      timestamp: t - 40,
      type: "CLIENT_DNS_OK",
      text: "Status code 0 Successful",
      ap: "5c5b350eb31b",
      ssid: "CORP-WIFI",
      band: "5",
      channel: 149,
      reason: null,
      negative: false,
    },
    {
      timestamp: t - 90,
      type: "CLIENT_DHCP_TIMED_OUT",
      text: "DORA incomplete — no ACK",
      ap: "5c5b350eb31b",
      ssid: "CORP-WIFI",
      band: "5",
      channel: 149,
      reason: null,
      negative: true,
    },
    {
      timestamp: t - 140,
      type: "CLIENT_ASSOCIATION",
      text: "Associated",
      ap: "5c5b350eb31b",
      ssid: "CORP-WIFI",
      band: "5",
      channel: 149,
      reason: null,
      negative: false,
    },
    {
      timestamp: t - 148,
      type: "CLIENT_DEAUTHENTICATION",
      text: "Deauthenticated by AP",
      ap: "5c5b350a4412",
      ssid: "CORP-WIFI",
      band: "5",
      channel: 36,
      reason: 4,
      negative: true,
    },
    {
      timestamp: t - 420,
      type: "CLIENT_DEAUTHENTICATION",
      text: "4-way handshake timeout",
      ap: "5c5b350a4412",
      ssid: "CORP-WIFI",
      band: "5",
      channel: 36,
      reason: 15,
      negative: true,
    },
    {
      timestamp: t - 900,
      type: "CLIENT_ROAMED",
      text: "Roamed from 5c5b350a4412",
      ap: "5c5b350eb31b",
      ssid: "CORP-WIFI",
      band: "5",
      channel: 149,
      reason: null,
      negative: false,
    },
    {
      timestamp: t - 1800,
      type: "CLIENT_AUTHORIZATION",
      text: "Authorized",
      ap: "5c5b350a4412",
      ssid: "CORP-WIFI",
      band: "5",
      channel: 36,
      reason: null,
      negative: false,
    },
    {
      timestamp: t - 3600,
      type: "CLIENT_DISASSOCIATION",
      text: "STA leaving BSS",
      ap: "5c5b350a4412",
      ssid: "CORP-WIFI",
      band: "2.4",
      channel: 11,
      reason: 8,
      negative: true,
    },
  ];

  const sessions: ClientSession[] = [
    {
      ap: "5c5b350eb31b",
      ssid: "CORP-WIFI",
      band: "5",
      connect: t - 214,
      disconnect: null,
      duration: 214,
    },
    {
      ap: "5c5b350a4412",
      ssid: "CORP-WIFI",
      band: "5",
      connect: t - 480,
      disconnect: t - 148,
      duration: 28,
    },
    {
      ap: "5c5b350a4412",
      ssid: "CORP-WIFI",
      band: "5",
      connect: t - 900,
      disconnect: t - 840,
      duration: 44,
    },
    {
      ap: "5c5b350eb31b",
      ssid: "CORP-WIFI",
      band: "5",
      connect: t - 7200,
      disconnect: t - 3600,
      duration: 3580,
    },
  ];

  const nwJ = opts?.jitter ? Math.max(0, Math.min(8, Math.round(Math.random() * 4))) : 0;
  const apRadio: ApRadio = {
    apMac: "a8f7d9f096f0",
    apName: "MISS688-AP-F1-f0:96:f0",
    apNameHint: "MISS688-AP-F1-f0:96:f0",
    source: "marvis",
    dwellSeconds: 3580,
    dwellShare: 0.9,
    bandHint: "5",
    marvisMentioned: true,
    marvisAps: ["a8f7d9f096f0"],
    marvisName: "MISS688-AP-F1-f0:96:f0",
    deviceId: "00000000-0000-0000-1000-a8f7d9f096f0",
    selectionNote:
      "Marvis named MISS688-AP-F1-f0:96:f0 as the AP this client used most of the time. Chart is that radio (a8:f7:d9:f0:96:f0).",
    fallback: false,
    status: "connected",
    band: "5",
    radio: {
      channel: 144,
      bandwidth: 20,
      power: 8,
      numClients: 0,
      utilAll: 13,
      utilTx: 1,
      utilRxInBss: 8,
      utilRxOtherBss: 0,
      utilNonWifi: 0,
      utilUnknownWifi: 0,
      utilUndecodable: 0,
    },
    channels: [
      { channel: 100, site: 40, external: 0, nonWifi: 0, serving: false },
      { channel: 104, site: 15, external: 0, nonWifi: 0, serving: false },
      { channel: 108, site: 47, external: 0, nonWifi: 0, serving: false },
      { channel: 112, site: 19, external: 0, nonWifi: 0, serving: false },
      { channel: 116, site: 34, external: 0, nonWifi: 0, serving: false },
      { channel: 132, site: 28, external: 0, nonWifi: 0, serving: false },
      { channel: 136, site: 17, external: 0, nonWifi: 0, serving: false },
      { channel: 140, site: 24, external: 0, nonWifi: 2, serving: false },
      { channel: 144, site: 9, external: 0, nonWifi: 0, serving: true },
      { channel: 149, site: 29, external: 0, nonWifi: 0, serving: false },
      { channel: 153, site: 16, external: 0, nonWifi: 70 + nwJ, serving: false },
      { channel: 157, site: 20, external: 0, nonWifi: 0, serving: false },
      { channel: 161, site: 0, external: 5, nonWifi: 75, serving: false },
      { channel: 165, site: 0, external: 2, nonWifi: 98, serving: false },
    ],
    scope: "ap",
    unavailable: null,
  };

  return {
    demo: true,
    host: "api.gc2.mist.com",
    orgId: "demo-org",
    siteId: "demo-site",
    siteName: "Barrie HQ — Floor 2",
    mac: DEMO_MAC,
    duration: "1d",
    online: true,
    stats,
    sightings: [stats],
    events,
    sessions,
    marvisText: JSON.stringify(
      {
        category: "Wireless connectivity",
        reason: "Weak RSSI and handshake timeouts on AP 5c5b350a4412",
        description:
          " The AP is currently online. Client VALERIE-MBP was connected to MISS688-AP-F1-f0:96:f0 most of the time. Client repeatedly deauthenticates (reason 4 inactivity, reason 15 4-way timeout) then reassociates on a farther AP with RSSI −81 dBm and SNR 11 dB.",
        recommendation:
          "Check AP 5c5b350a4412 radio / channel 36, verify PSK, and add coverage toward the client’s last location. DHCP timeouts after rejoin suggest the client is also struggling L3 on the new AP.",
      },
      null,
      2,
    ),
    marvisUnavailable: false,
    verdict: buildVerdict(stats, events, sessions, apRadio),
    fetchedAt: Date.now(),
    apRadio,
  };
}
