import { buildVerdict } from "./classify.ts";
import { annotateRadioEvents, buildRadioStore, pickCall, pickRrmEvent, radarSessionAlerts } from "./radio.ts";
import type { ApRadio, ClientEvent, ClientSession, ClientStats, DiagnoseResult } from "./types.ts";

const now = () => Math.floor(Date.now() / 1000);

/** Locally-administered demo identifiers — not a real site or station. */
export const DEMO_MAC = "0a0027c1e001";
const AP_CURRENT = "0a0027aa1102";
const AP_PEER = "0a0027aa1103";
const AP_CURRENT_NAME = "DEMO-AP-F2-aa:11:02";
const AP_PEER_NAME = "DEMO-AP-F2-aa:11:03";

export function buildDemoResult(opts?: { jitter?: boolean }): DiagnoseResult {
  const t = now();
  const jitter = opts?.jitter ? Math.round((Math.random() - 0.5) * 6) : 0;
  const stats: ClientStats = {
    mac: DEMO_MAC,
    hostname: "DEMO-MBP",
    manufacture: "Apple",
    os: "macOS 15.5",
    model: "MacBookPro18,3",
    ssid: "CORP-WIFI",
    vlan: 40,
    ip: "10.40.12.88",
    ap: AP_CURRENT,
    band: "5",
    channel: 149,
    proto: "ax",
    rssi: -81 + jitter,
    snr: Math.max(6, 11 + Math.round(jitter / 2)),
    txRate: 58,
    rxRate: 48,
    uptime: 140,
    lastSeen: t - 12,
    txBytes: 1843200,
    rxBytes: 9216000,
    username: "demo.user",
    keyMgmt: "WPA2-PSK",
    txRetries: 214,
    rxRetries: 88,
    dualBand: true,
  };

  const events: ClientEvent[] = [
    {
      timestamp: t - 40,
      type: "CLIENT_DNS_OK",
      text: "Status code 0 Successful",
      ap: AP_CURRENT,
      ssid: "CORP-WIFI",
      band: "5",
      channel: 149,
      reason: null,
      negative: false,
    },
    {
      timestamp: t - 90,
      type: "CLIENT_DHCP_TIMED_OUT",
      text: "DORA incomplete — no ACK",
      ap: AP_CURRENT,
      ssid: "CORP-WIFI",
      band: "5",
      channel: 149,
      reason: null,
      negative: true,
    },
    {
      timestamp: t - 140,
      type: "CLIENT_ASSOCIATION",
      text: "Associated",
      ap: AP_CURRENT,
      ssid: "CORP-WIFI",
      band: "5",
      channel: 149,
      reason: null,
      negative: false,
    },
    {
      timestamp: t - 148,
      type: "CLIENT_DEAUTHENTICATION",
      text: "Deauthenticated by AP",
      ap: AP_PEER,
      ssid: "CORP-WIFI",
      band: "5",
      channel: 36,
      reason: 4,
      negative: true,
    },
    {
      timestamp: t - 420,
      type: "CLIENT_DEAUTHENTICATION",
      text: "4-way handshake timeout",
      ap: AP_PEER,
      ssid: "CORP-WIFI",
      band: "5",
      channel: 36,
      reason: 15,
      negative: true,
    },
    {
      timestamp: t - 900,
      type: "CLIENT_ROAMED",
      text: `Roamed from ${AP_PEER}`,
      ap: AP_CURRENT,
      ssid: "CORP-WIFI",
      band: "5",
      channel: 149,
      reason: null,
      negative: false,
    },
    {
      timestamp: t - 1800,
      type: "CLIENT_AUTHORIZATION",
      text: "Authorized",
      ap: AP_PEER,
      ssid: "CORP-WIFI",
      band: "5",
      channel: 36,
      reason: null,
      negative: false,
    },
    {
      timestamp: t - 3600,
      type: "CLIENT_DISASSOCIATION",
      text: "STA leaving BSS",
      ap: AP_PEER,
      ssid: "CORP-WIFI",
      band: "2.4",
      channel: 11,
      reason: 8,
      negative: true,
    },
  ];

  const sessions: ClientSession[] = [
    {
      ap: AP_CURRENT,
      apName: AP_CURRENT_NAME,
      ssid: "CORP-WIFI",
      band: "5",
      connect: t - 140,
      disconnect: null,
      duration: 140,
    },
    {
      ap: AP_PEER,
      apName: AP_PEER_NAME,
      ssid: "CORP-WIFI",
      band: "5",
      connect: t - 480,
      disconnect: t - 148,
      duration: 332,
    },
    {
      ap: AP_PEER,
      apName: AP_PEER_NAME,
      ssid: "CORP-WIFI",
      band: "5",
      connect: t - 900,
      disconnect: t - 840,
      duration: 44,
    },
    {
      ap: AP_CURRENT,
      apName: AP_CURRENT_NAME,
      ssid: "CORP-WIFI",
      band: "5",
      connect: t - 7200,
      disconnect: t - 3600,
      duration: 3580,
    },
  ];

  const nwJ = opts?.jitter ? Math.max(0, Math.min(8, Math.round(Math.random() * 4))) : 0;
  const apRadio: ApRadio = {
    apMac: AP_CURRENT,
    apName: AP_CURRENT_NAME,
    apNameHint: AP_CURRENT_NAME,
    source: "marvis",
    dwellSeconds: 3794,
    dwellShare: 0.98,
    bandHint: "5",
    marvisMentioned: true,
    marvisAps: [AP_CURRENT],
    marvisName: AP_CURRENT_NAME,
    deviceId: `00000000-0000-0000-1000-${AP_CURRENT}`,
    selectionNote: `Marvis named ${AP_CURRENT_NAME} as the AP this client used most of the time. Chart is that radio (0a:00:27:aa:11:02).`,
    fallback: false,
    status: "connected",
    band: "5",
    radio: {
      channel: 144,
      bandwidth: 20,
      power: 8,
      numClients: 0,
      utilAll: 12,
      utilTx: 1,
      utilRxInBss: 9,
      utilRxOtherBss: 0,
      utilNonWifi: 0,
      utilUnknownWifi: 0,
      utilUndecodable: 0,
    },
    channels: [
      { channel: 100, site: 40, external: 0, nonWifi: 0, serving: false },
      { channel: 104, site: 15, external: 0, nonWifi: 0, serving: false },
      { channel: 108, site: 47, external: 0, nonWifi: 0, serving: false },
      { channel: 112, site: 19, external: 0, nonWifi: 0, serving: false },
      { channel: 116, site: 34, external: 0, nonWifi: 0, serving: false },
      { channel: 132, site: 28, external: 0, nonWifi: 0, serving: false },
      { channel: 136, site: 17, external: 0, nonWifi: 0, serving: false },
      { channel: 140, site: 24, external: 0, nonWifi: 2, serving: false },
      { channel: 144, site: 9, external: 0, nonWifi: 0, serving: true },
      { channel: 149, site: 29, external: 0, nonWifi: 0, serving: false },
      { channel: 153, site: 16, external: 0, nonWifi: 70 + nwJ, serving: false },
      { channel: 157, site: 20, external: 0, nonWifi: 0, serving: false },
      { channel: 161, site: 0, external: 5, nonWifi: 75, serving: false },
      { channel: 165, site: 0, external: 2, nonWifi: 98, serving: false },
    ],
    scope: "ap",
    unavailable: null,
  };

  const radioEvents = annotateRadioEvents(
    [
      pickRrmEvent({
        timestamp: t - 156,
        ap: AP_PEER,
        band: "5",
        event: "rrm-radar",
        channel: 149,
        pre_channel: 36,
        bandwidth: 80,
        pre_bandwidth: 80,
        power: 17,
        pre_power: 17,
        usage: "5",
        pre_usage: "5",
        apName: AP_PEER_NAME,
      }),
      pickRrmEvent({
        timestamp: t - 80,
        ap: AP_CURRENT,
        band: "5",
        event: "triggered-site_rrm",
        channel: 144,
        pre_channel: 144,
        bandwidth: 20,
        pre_bandwidth: 20,
        power: 8,
        pre_power: 14,
        usage: "5",
        pre_usage: "5",
        apName: AP_CURRENT_NAME,
      }),
      pickRrmEvent({
        timestamp: t - 90000,
        ap: AP_CURRENT,
        band: "5",
        event: "interference-ap-non-wifi",
        channel: 144,
        pre_channel: 153,
        bandwidth: 20,
        pre_bandwidth: 80,
        power: 8,
        pre_power: 14,
        usage: "5",
        pre_usage: "5",
        apName: AP_CURRENT_NAME,
      }),
      pickRrmEvent({
        timestamp: t - 2 * 86400 - 3600,
        ap: AP_CURRENT,
        band: "5",
        event: "scheduled-site_rrm",
        channel: 144,
        pre_channel: 144,
        bandwidth: 20,
        pre_bandwidth: 20,
        power: 8,
        pre_power: 8,
        usage: "5",
        pre_usage: "5",
        apName: AP_CURRENT_NAME,
      }),
      pickRrmEvent({
        timestamp: t - 4 * 86400,
        ap: "0a0027aa1105",
        band: "5",
        event: "neighbor-ap-down",
        channel: 108,
        pre_channel: 108,
        bandwidth: 40,
        pre_bandwidth: 40,
        power: 8,
        pre_power: 8,
        usage: "5",
        pre_usage: "5",
        apName: "DEMO-AP-F2-aa:11:05",
      }),
    ],
    events,
    sessions,
    stats,
  );

  const calls = [
    pickCall({
      app: "teams",
      mac: DEMO_MAC,
      meeting_id: "demo-teams-1",
      start_time: t - 210,
      end_time: t - 35,
      audio_quality: 2,
      video_quality: 3,
      rating: 2,
    }),
    pickCall({
      app: "teams",
      mac: DEMO_MAC,
      meeting_id: "demo-teams-2",
      start_time: t - 86400 - 3600,
      end_time: t - 86400 - 1800,
      audio_quality: 5,
      video_quality: 5,
      rating: 5,
    }),
    pickCall({
      app: "zoom",
      mac: DEMO_MAC,
      meeting_id: "demo-zoom-1",
      start_time: t - 3 * 3600,
      end_time: t - 3 * 3600 + 2400,
      audio_quality: 4,
      video_quality: 4,
    }),
  ];
  const store = buildRadioStore(
    radioEvents,
    sessions.flatMap((s) => [s.ap, s.bssid ?? ""]),
  );
  const radarAlerts = radarSessionAlerts(radioEvents, sessions, calls, apRadio, store);
  const clientRadarEvents = store.clientRadarEvents(sessions);

  return {
    demo: true,
    host: "api.gc2.mist.com",
    orgId: "demo-org",
    siteId: "demo-site",
    siteName: "Sample HQ — Floor 2",
    mac: DEMO_MAC,
    duration: "1d",
    online: true,
    stats,
    sightings: [stats],
    events,
    sessions,
    marvisText: JSON.stringify(
      {
        results: [
          {
            category: "Device Health",
            text: ` The AP is currently online. Client DEMO-MBP was connected to ${AP_CURRENT_NAME} most of the time.`,
            site_id: "demo-site",
          },
          {
            category: "Wireless connectivity",
            text: "Weak RSSI and handshake timeouts on AP 0a0027aa1103. Client repeatedly deauthenticates then reassociates.",
          },
        ],
        start: t - 86400,
        end: t,
      },
      null,
      2,
    ),
    marvisUnavailable: false,
    verdict: buildVerdict(stats, events, sessions, apRadio, radioEvents, calls, store),
    fetchedAt: Date.now(),
    apRadio,
    radioEvents,
    radioEventsUnavailable: null,
    clientRadarEvents,
    radioStoreStats: {
      scanned: store.scanned,
      dropped: store.dropped,
      radars: store.radars.length,
      kept: store.kept.length,
      clientHits: clientRadarEvents.length,
    },
    calls,
    callsUnavailable: null,
    radarAlerts,
  };
}
